services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: dyzulk-devcontainer
    user: node
    working_dir: /workspaces/dyzulk
    volumes:
      - ..:/workspaces/dyzulk
      # Isolate node_modules between host and container
      - /workspaces/dyzulk/node_modules
      - /workspaces/dyzulk/apps/web/node_modules
      - /workspaces/dyzulk/apps/docs/node_modules
      - /workspaces/dyzulk/packages/ui/node_modules
      - /workspaces/dyzulk/packages/eslint-config/node_modules
      - /workspaces/dyzulk/packages/typescript-config/node_modules
      - dyzulk-pnpm-store:/home/node/.local/share/pnpm/store
    ports:
      - "30000:3000"
      - "30001:3001"
    command: bash -c "bash ./.devcontainer/post-create.sh && pnpm build && pnpm start"
    restart: unless-stopped

volumes:
  dyzulk-pnpm-store:
