// 5 Mock Applications for Dyzulk Dashboard Demo
export const MOCK_APPLICATIONS = [
  {
    id: "app-1",
    name: "laravel",
    env: "production",
    repo: "dyzulk/laravel",
    domain: "Domain pending",
    branch: "main",
    status: "never-deployed",
    timeAgo: "9 minutes ago",
    tech: "laravel",
    commitDesc: "Initial commit by Laravel Cloud",
  },
  {
    id: "app-2",
    name: "livewire-starter-kit",
    env: "production",
    repo: "dyzulk/livewire-starter-kit",
    domain: "Domain pending",
    branch: "main",
    status: "never-deployed",
    timeAgo: "10 minutes ago",
    tech: "laravel", // livewire is laravel tech stack in this illustration
    commitDesc: "Initial commit by Laravel Cloud",
  },
  {
    id: "app-3",
    name: "react-starter-kit",
    env: "production",
    repo: "dyzulk/react-starter-kit",
    domain: "react-starter-kit-production-2z9fr2.laravel.cloud",
    branch: "main",
    status: "deployed",
    timeAgo: "Never deployed",
    tech: "react",
    commitDesc: "Initial commit by Laravel Cloud",
  },
  {
    id: "app-4",
    name: "svelte-starter-kit",
    env: "production",
    repo: "dyzulk/svelte-starter-kit",
    domain: "Domain pending",
    branch: "main",
    status: "never-deployed",
    timeAgo: "10 minutes ago",
    tech: "svelte",
    commitDesc: "Initial commit by Laravel Cloud",
  },
  {
    id: "app-5",
    name: "vue-starter-kit",
    env: "production",
    repo: "dyzulk/vue-starter-kit",
    domain: "vue-starter-kit-production-u8u5tc.laravel.cloud",
    branch: "main",
    status: "deployed",
    timeAgo: "12 minutes ago",
    tech: "vue",
    commitDesc: "Initial commit by Laravel Cloud",
  },
];

// 5 Mock Deployments for Dyzulk Dashboard Demo
export const MOCK_DEPLOYMENTS = [
  {
    id: "dep-1",
    commit: "a3acb27",
    appName: "svelte-starter-kit",
    env: "production",
    description: "Initial commit by Laravel Cloud",
    branch: "main",
    timeAgo: "just now",
    author: "DyzulkDev",
    status: "deploying",
  },
  {
    id: "dep-2",
    commit: "fb9edd7",
    appName: "vue-starter-kit",
    env: "production",
    description: "Initial commit by Laravel Cloud",
    branch: "main",
    timeAgo: "2 minutes ago",
    author: "DyzulkDev",
    status: "deploying",
  },
  {
    id: "dep-3",
    commit: "cc37f44",
    appName: "react-starter-kit",
    env: "production",
    description: "Initial commit by Laravel Cloud",
    branch: "main",
    timeAgo: "a month ago",
    author: "DyzulkDev",
    status: "success",
  },
  {
    id: "dep-4",
    commit: "485d683",
    appName: "react-starter-kit",
    env: "production",
    description: "Initial commit by Laravel Cloud",
    branch: "main",
    timeAgo: "a month ago",
    author: "",
    status: "success",
  },
  {
    id: "dep-5",
    commit: "91ab912",
    appName: "express-api",
    env: "production",
    description: "Update endpoint routes",
    branch: "main",
    timeAgo: "2 hours ago",
    author: "DyzulkDev",
    status: "success",
  },
];
